kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: ${PROJECT_NAME_SLUG}
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: ${PROJECT_NAME_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_NAME}
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_URI}
spec:
  scaleTargetRef:
    kind: Deployment
    name: ${PROJECT_NAME_SLUG}
    apiVersion: apps/v1
  minReplicas: ${MIN_REPLICAS}
  maxReplicas: ${MAX_REPLICAS}
  targetCPUUtilizationPercentage: ${SCALING_BY_CPU_PERC}
