import './globals.css'
import type {Metadata} from 'next'
import {inter} from './utils/fonts'
import React from "react";
import App from "@/app/page";



export const metadata: Metadata = {
    title: 'HUB DE OFERTAS',
    description: 'Generated by create next app',
}


export default function RootLayout({children}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body className={inter.className}>
                <App>
                    {children}
                </App>
            </body>
        </html>
    )
}
