name: 🔁 CI - Experimentos de CI/CD (GHA Validation)

on:
  push:
    branches: [ main ]
    paths:
      # Roda a pipeline somente se houver mudanças na pasta 'cicd' ou no próprio workflow
      - 'cicd/**'
      - '.github/workflows/cicd_ci.yml'

jobs:
  validate_and_run_smoke:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v4

      - name: 🔍 Validação da Sintaxe YAML dos Workflows
        # Esta step garante que todos os arquivos .yml de CI/CD estejam sintaticamente corretos.
        run: |
          echo "Verificando sintaxe YAML nos workflows..."
          # Instala uma ferramenta de validação YAML
          pip install yamllint
          yamllint .github/workflows/*.yml

      - name: 🏃 Rodar Smoke Test Genérico (Exemplo Shell Script)
        # Demonstra um script simples de validação ou build que poderia estar na pasta cicd
        run: |
          echo "CI/CD Smoke Test Iniciado..."
          ls -F
          echo "Construindo/Validando artefato de CI/CD..."
          # Adicione aqui qualquer comando de build/validação que faça sentido para sua pasta 'cicd'
          echo "CI/CD Smoke Test Concluído com Sucesso."
        working-directory: cicd