name: 🤖 CI - Testes BDD CodeceptJS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
    paths:
      - 'codeceptjs/**'
      - '.github/workflows/codeceptjs_ci.yml'

jobs:
  run_node_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v5
        
      - name: ⚙️ Configurar Node.js (v24)
        uses: actions/setup-node@v5
        with:
          node-version: 24
          
      - name: 📦 Instalar Dependências (CodeceptJS)
        run: npm install
        working-directory: codeceptjs
        
      - name: 🌐 Instalar Browser Chromium (Contornando Permissão)
        # Usar 'npm exec' força o node a rodar o pacote com as permissões corretas do escopo local
        run: npm exec playwright install chromium
        working-directory: codeceptjs
        env:
          CI: true
        
      - name: 🏃 Rodar Testes CodeceptJS
        run: npm exec codeceptjs run --verbose
        working-directory: codeceptjs
        env:
          HEADLESS: true
          CI: true