name: 🤖 CI - Testes BDD CodeceptJS

on:
  push:
    branches: [ main ]
    paths:
      - 'codeceptjs/**'
      - '.github/workflows/codeceptjs_ci.yml'

jobs:
  run_node_tests:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v4
        
      - name: ⚙️ Configurar Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: 📦 Instalar Dependências (CodeceptJS)
        run: npm install
        working-directory: codeceptjs

      - name: 🔒 Corrigir Permissões do Binário
        run: chmod +x ./node_modules/.bin/codeceptjs
        working-directory: codeceptjs
        
      - name: 🏃 Rodar Testes CodeceptJS
        run: npm exec -- codeceptjs run --steps
        working-directory: codeceptjs