name: 🧪 CI - Testes E2E Cypress

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
    paths:
      - 'cypress/**'
      - '.github/workflows/cypress_ci.yml' # Certifique-se de que o nome do arquivo aqui está idêntico ao seu real

jobs:
  run_cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v5
        
      - name: ⚙️ Configurar Node.js (v24)
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📦 Instalar Ferramentas Globais
        run: npm install -g @lhci/cli
        
      - name: 📦 Instalar Dependências do Cypress
        run: npm install
        working-directory: cypress

      - name: 🏃 Executando Testes Cypress
        id: cypress_tests
        run: npx cypress run --headless
        working-directory: cypress

      - name: 📊 Gerar Relatórios Mochawesome
        if: always()
        # O || true garante que pequenas instabilidades do gerador de arquivos não quebrem seu CI
        run: npx mochawesome-merge cypress/mochawesome-report/*.json > cypress/mochawesome.json || true && npx marge cypress/mochawesome.json -f report -o cypress/mochawesome-report || true
        working-directory: cypress

      - name: ⬆️ Publicar Relatórios e Evidências
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: cypress-report
          path: cypress/mochawesome-report
          retention-days: 30