name: 📊 CI - Scripts k6 (Performance)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'k6/**'
      - '.github/workflows/k6.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'k6/**'
      - '.github/workflows/k6.yml'

jobs:
  run_k6_smoke_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v5

      - name: 🧪 Instala k6 Manualmente (Contorno de Action)
        run: sudo snap install k6

      - name: 🏃 Rodar Teste de Fumaça (Smoke Test)
        run: /snap/bin/k6 run script.js
        working-directory: k6