name: 🐍 CI - Testes Python (Pytest)

on:
  push:
    branches: [ main, develop ] # Roda o CI ao commitar na main ou na develop
  pull_request:
    branches: [ main ] # Roda o CI também quando você abrir um PR para juntar a develop na main
    paths:
      - 'python/**'
      - '.github/workflows/python_ci.yml'

jobs:
  run_pytest_tests:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v5

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: 📦 Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: python

      - name: 🏃 Rodar Testes com Pytest
        run: python -m pytest
        working-directory: python