name: ♦️ CI - Testes Ruby

on:
  push:
    branches: [ main, develop ] # Roda o CI ao commitar na main ou na develop
  pull_request:
    branches: [ main ] # Roda o CI também quando você abrir um PR para juntar a develop na main
    paths:
      - 'ruby/**'
      - '.github/workflows/ruby_ci.yml'

jobs:
  run_rspec_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v5

      - name: ♦️ Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: 📦 Instala Dependências (Bundle Install)
        run: bundle install 
        working-directory: ruby

      - name: 🏃 Rodar Testes Ruby (RSpec/Cucumber)
        run: bundle exec rspec spec/
        working-directory: ruby