name: 🔌 CI - Configurações de Mocking (WireMock)

on:
  push:
    branches: [ main ]
    paths:
      # Roda a pipeline somente se houver mudanças na pasta 'wiremock' ou no próprio workflow
      - 'wiremock/**'
      - '.github/workflows/wiremock_ci.yml'

jobs:
  validate_wiremock_config:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v4

      - name: ☕ Configurar Java (v17)
        # WireMock é um JAR que roda em Java e requer o JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🏃 Validação de Sanidade do WireMock
        # Esta step simula o comando de inicialização, validando se o JAR e as configs existem.
        # Adicione o comando real se você mantiver o JAR no repo, ou use Maven/Gradle se for biblioteca.
        run: |
          echo "Verificando se o JAR do WireMock e as configurações JSON estão acessíveis..."
          # Exemplo de comando se você tiver o JAR salvo (MUITO GRANDE para GitHub)
          # java -jar wiremock-standalone.jar --port 8080 --root-dir src/main/resources &
          
          # Alternativa: Apenas checa se os arquivos essenciais estão na pasta
          test -d src/main/resources/mappings || { echo "ERRO: Pasta 'mappings' não encontrada."; exit 1; }
          
          echo "Configurações WireMock validadas. A sintaxe JSON é validada durante a inicialização (se executado)."
        working-directory: wiremock