name: 📱 CI - Testes XCUITest/iOS

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'xcuitest/**'
      - '.github/workflows/xcuitest.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'xcuitest/**'
      - '.github/workflows/xcuitest.yml'

jobs:
  run_xcuitest:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v5

      # - name: 🏃 Rodar Testes XCUITest com xcodebuild
      #   run: |
      #     xcodebuild clean test \
      #     -project xcuitestProject.xcodeproj \
      #     -scheme MyApplicationsUITests \
      #     -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
      #   working-directory: xcuitest